In [1]:
#!/usr/bin/python
# -*- coding: UTF-8 -*-
import pandas as pd
import numpy as np
import pprint

In [2]:
#控制中文标题对齐
pd.set_option('display.unicode.ambiguous_as_wide', True)
pd.set_option('display.unicode.east_asian_width', True)

#显示所有列
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)    #设置整体宽度
pd.set_option('display.max_rows',20)   #设置最大行数
pd.set_option('display.max_columns', 100) #设置最大列数

# 读取excel，可以直接读取本地文件，也可以读取网络链接的文件
#header=0表示第0行是标题，第一行是数据
#names:指定自定义的列名

In [3]:
df=pd.read_excel("http://www.csindex.com.cn/uploads/file/autofile/indicator/000905indicator.xls",header=0,names=["Date","Index Code","Index Chinese Name(Full)","Index Chinese Name","Index English Name(Full)","Index English Name","P/E1","P/E2","D/P1","D/P2"],encoding = 'utf_8')
print(df)

         Date  Index Code Index Chinese Name(Full) Index Chinese Name Index English Name(Full) Index English Name   P/E1   P/E2  D/P1  D/P2
0  2020-07-10         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500    NaN    NaN   NaN   NaN
1  2020-07-09         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  25.84  26.94  1.05  0.98
2  2020-07-08         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  25.23  26.30  1.08  1.00
3  2020-07-07         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  24.67  25.68  1.10  1.03
4  2020-07-06         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  24.38  25.38  1.11  1.04
..        ...         ...                      ...                ...                      ...                ...    ...    ...   ...   ...
18 2020-06-16         905          中证小盘500指数            中证50

# 保存dataframe到csv文件
”utf-8“ 是以字节为编码单元,它的字节顺序在所有系统中都是一样的,没有字节序问题,因此它不需要BOM.

"uft-8-sig"中sig全拼为 signature 也就是"带有签名的utf-8", 因此"utf-8-sig"读取带有BOM的"utf-8文件时"会把BOM单独处理,与文本内容隔离开

In [4]:
df.to_csv("stock.csv",encoding='utf_8_sig')

# 保存dataframe到excel文件

In [5]:
df.to_excel("stock.xls",encoding='utf_8')

# 读取csv文件，使用自定义的列名

In [6]:
df=pd.read_csv("stock.csv",header=0,encoding='utf_8')
print(df)

    Unnamed: 0        Date  Index Code Index Chinese Name(Full) Index Chinese Name Index English Name(Full) Index English Name   P/E1   P/E2  D/P1  D/P2
0            0  2020-07-10         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500    NaN    NaN   NaN   NaN
1            1  2020-07-09         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  25.84  26.94  1.05  0.98
2            2  2020-07-08         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  25.23  26.30  1.08  1.00
3            3  2020-07-07         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  24.67  25.68  1.10  1.03
4            4  2020-07-06         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  24.38  25.38  1.11  1.04
..         ...         ...         ...                      ...                ...                      ...               

# 将数据以压缩格式存储

In [7]:
h5 = pd.HDFStore("Preprocessing",'w', complevel=4, complib='blosc')
h5['data'] = df
h5.close()

# 载入数据

In [8]:
h5=pd.HDFStore("Preprocessing","r")
df=h5["data"]
h5.close()
print(df)

    Unnamed: 0        Date  Index Code Index Chinese Name(Full) Index Chinese Name Index English Name(Full) Index English Name   P/E1   P/E2  D/P1  D/P2
0            0  2020-07-10         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500    NaN    NaN   NaN   NaN
1            1  2020-07-09         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  25.84  26.94  1.05  0.98
2            2  2020-07-08         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  25.23  26.30  1.08  1.00
3            3  2020-07-07         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  24.67  25.68  1.10  1.03
4            4  2020-07-06         905          中证小盘500指数            中证500   CSI Smallcap 500 Index            CSI 500  24.38  25.38  1.11  1.04
..         ...         ...         ...                      ...                ...                      ...               

# 用等长列表组成的字典来创建dataframe

In [9]:
data={'c':['1','2'],'a':['5','6']}
df=pd.DataFrame(data)
print(df,"\n")

print("如果指定了columns名称，则会按照指定顺序创建")
df=pd.DataFrame(data,columns=['a','c'])
print(df,"\n")

   c  a
0  1  5
1  2  6 

如果指定了columns名称，则会按照指定顺序创建
   a  c
0  5  1
1  6  2 



# 根据嵌套字典（字典的值也是字典）创建DataFrame

In [10]:
nest_dict={'shanghai':{2015:100,2016:101,2017:102},'beijing':{2015:102,2016:103,2017:104}}  
df=pd.DataFrame(nest_dict)
print(df,"\n")

      shanghai  beijing
2015       100      102
2016       101      103
2017       102      104 



# 根据numpy数组创建dataframe
dataframe中索引的概念与数据库不同，,index为行索引（行标题）,columns为列索引（相当于字段名）

In [11]:
df=pd.DataFrame(np.arange(16).reshape((4,4)),index=['a','b','c','d'],columns=['one','two','three','four'])
print(df)
print("shape：",df.shape)
print("行数：",df.index.size)
print("列数：",df.columns.size)

   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15
shape： (4, 4)
行数： 4
列数： 4


# 基于label进行索引

In [12]:
print("\n行标题为a的行：")
print(df.loc["a",:])

print("\n行标题为a的行：")
print(df.loc["a"])

print("\n行标题为a，列标题为one数据：")
print(df.loc["a","one"])

print("\n行标题为a~c的行：")
print(df.loc["a":"c",:])

print("\n选择多列")
print(df.loc["a",["one","two"]])


行标题为a的行：
one      0
two      1
three    2
four     3
Name: a, dtype: int32

行标题为a的行：
one      0
two      1
three    2
four     3
Name: a, dtype: int32

行标题为a，列标题为one数据：
0

行标题为a~c的行：
   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11

选择多列
one    0
two    1
Name: a, dtype: int32


# 基于位置进行索引

In [13]:
print("第1行：")
print(df.iloc[0])

print("\n第1行")
print(df.iloc[0,:])

print("\n第1行，第1列：")
print(df.iloc[1,0])

print("\n切片1~2行")
print(df.iloc[0:2,:])

print("\n选择多列")
print(df.iloc[:,[0,1]])

第1行：
one      0
two      1
three    2
four     3
Name: a, dtype: int32

第1行
one      0
two      1
three    2
four     3
Name: a, dtype: int32

第1行，第1列：
4

切片1~2行
   one  two  three  four
a    0    1      2     3
b    4    5      6     7

选择多列
   one  two
a    0    1
b    4    5
c    8    9
d   12   13


# 混合lable与位置进行索引

In [14]:
df.iloc[0].loc["one"]=12
print(df.iloc[0].loc["one"])

12


# 按行遍历
row[0]内存储的是行索引

In [15]:
for index,row in df.iterrows():
    print(index,row["one"], row["two"])

a 12 1
b 4 5
c 8 9
d 12 13


# 增加1列,标题为c，内容都为1

In [16]:
df.loc[:,"c"]=1
print(df)

   one  two  three  four  c
a   12    1      2     3  1
b    4    5      6     7  1
c    8    9     10    11  1
d   12   13     14    15  1


# 删除c列

In [17]:
df=df.drop(["c"],axis=1)
print(df)

   one  two  three  four
a   12    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15


# 修改列名

In [18]:
df.rename(columns={'three':'THREE', 'four':'FOUR'}, inplace = True)
print(df)

   one  two  THREE  FOUR
a   12    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15


# 增加1行

In [19]:
df.loc["e",:]=[9,10,11,12]
print(df)

    one   two  THREE  FOUR
a  12.0   1.0    2.0   3.0
b   4.0   5.0    6.0   7.0
c   8.0   9.0   10.0  11.0
d  12.0  13.0   14.0  15.0
e   9.0  10.0   11.0  12.0


# 删除1行

In [20]:
df=df.drop(["e"],axis=0)
print(df)

    one   two  THREE  FOUR
a  12.0   1.0    2.0   3.0
b   4.0   5.0    6.0   7.0
c   8.0   9.0   10.0  11.0
d  12.0  13.0   14.0  15.0


# 删除重复的行

In [21]:
df.drop_duplicates()
print(df)

    one   two  THREE  FOUR
a  12.0   1.0    2.0   3.0
b   4.0   5.0    6.0   7.0
c   8.0   9.0   10.0  11.0
d  12.0  13.0   14.0  15.0


# 排序

In [22]:
a=df.sort_values(by="one" , ascending=False)
print(a,"\n")

a=df.sort_values(by=["one","two"] , ascending=False)
print(a,"\n")

    one   two  THREE  FOUR
a  12.0   1.0    2.0   3.0
d  12.0  13.0   14.0  15.0
c   8.0   9.0   10.0  11.0
b   4.0   5.0    6.0   7.0 

    one   two  THREE  FOUR
d  12.0  13.0   14.0  15.0
a  12.0   1.0    2.0   3.0
c   8.0   9.0   10.0  11.0
b   4.0   5.0    6.0   7.0 



# 多条件过滤数据

In [23]:
df2=df[(df.one>4)&(df.two<13)]
print(df,"\n")
print(df2,"\n")

    one   two  THREE  FOUR
a  12.0   1.0    2.0   3.0
b   4.0   5.0    6.0   7.0
c   8.0   9.0   10.0  11.0
d  12.0  13.0   14.0  15.0 

    one  two  THREE  FOUR
a  12.0  1.0    2.0   3.0
c   8.0  9.0   10.0  11.0 



# 保留>4的数据，其它数据赋值NaN

In [24]:
print(df,"\n")
df.one=df.one.where(df.one>4)
print(df)

    one   two  THREE  FOUR
a  12.0   1.0    2.0   3.0
b   4.0   5.0    6.0   7.0
c   8.0   9.0   10.0  11.0
d  12.0  13.0   14.0  15.0 

    one   two  THREE  FOUR
a  12.0   1.0    2.0   3.0
b   NaN   5.0    6.0   7.0
c   8.0   9.0   10.0  11.0
d  12.0  13.0   14.0  15.0


# 保留>4的数据，其它数据赋值1

In [25]:
df.one=df.one.where(df.one>4,1)
print(df)

    one   two  THREE  FOUR
a  12.0   1.0    2.0   3.0
b   1.0   5.0    6.0   7.0
c   8.0   9.0   10.0  11.0
d  12.0  13.0   14.0  15.0


# 替换=1的数据

In [26]:
df.one=df.one.replace(1,3)
print(df)

    one   two  THREE  FOUR
a  12.0   1.0    2.0   3.0
b   3.0   5.0    6.0   7.0
c   8.0   9.0   10.0  11.0
d  12.0  13.0   14.0  15.0


# 根据字典替换数据
不属于dict的值会被替换为NaN

In [27]:
df.four=df.FOUR.map({11:"女",3:"男"})
print(df)

    one   two  THREE  FOUR
a  12.0   1.0    2.0   3.0
b   3.0   5.0    6.0   7.0
c   8.0   9.0   10.0  11.0
d  12.0  13.0   14.0  15.0


D:\Program Files\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.


# dataframe转换为numpy

In [28]:
print(df.values)

[[12.  1.  2.  3.]
 [ 3.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


# 将列转换为索引

In [29]:
print("将one列转换为索引")
df2=df.set_index(['one'])
print(df2,"\n")

print("将one列,two均转换为索引")
df2=df.set_index(['one',"two"])
print(df2,"\n")

将one列转换为索引
       two  THREE  FOUR
one                    
12.0   1.0    2.0   3.0
3.0    5.0    6.0   7.0
8.0    9.0   10.0  11.0
12.0  13.0   14.0  15.0 

将one列,two均转换为索引
           THREE  FOUR
one  two              
12.0 1.0     2.0   3.0
3.0  5.0     6.0   7.0
8.0  9.0    10.0  11.0
12.0 13.0   14.0  15.0 



# 将索引转换为列

In [30]:
df.loc[:,"index"] = df.index
print(df)

    one   two  THREE  FOUR index
a  12.0   1.0    2.0   3.0     a
b   3.0   5.0    6.0   7.0     b
c   8.0   9.0   10.0  11.0     c
d  12.0  13.0   14.0  15.0     d


# merge连接dataframe
merge 只支持连接两个dataframe   
outer:取并集  
left:左外连接  
right:右外连接  
on : 指的是用于连接的列索引名称。必须存在右右两个DataFrame对象中，如果没有指定且其他参数也未指定则以两个DataFrame的列名交集做为连接键

In [58]:
df=pd.DataFrame(np.arange(16).reshape((4,4)),index=['a','b','c','d'],columns=['one','two','three','four'])
print(df)
df3=pd.merge(df, df, how='inner', on="one")
print(df3,"\n")

   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15
   one  two_x  three_x  four_x  two_y  three_y  four_y
0    0      1        2       3      1        2       3
1    4      5        6       7      5        6       7
2    8      9       10      11      9       10      11
3   12     13       14      15     13       14      15 



# concat连接dataframe
concat支持两个以上的dataframe 按索引 进行连接

In [55]:
df=pd.DataFrame(np.arange(16).reshape((4,4)),index=['a','b','c','d'],columns=['one','two','three','four'])
print(df,"\n")
print("将两个表按行进行合并")
df3=pd.concat([df, df],axis=1,join='inner')
print(df3)

   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15 

将两个表按行进行合并
   one  two  three  four  one  two  three  four
a    0    1      2     3    0    1      2     3
b    4    5      6     7    4    5      6     7
c    8    9     10    11    8    9     10    11
d   12   13     14    15   12   13     14    15


In [33]:
print("将两个表按列进行合并")
df3=pd.concat([df, df],axis=0)
print(df3,"\n")

将两个表按列进行合并
   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15 



# 数据类型转换
pd.to_numeric()能根据数据情况，自动转换为数字类型  
errors='ignore' 表示遇到错误时忽略，不转换  
errrors='coerce' 遇到错误时转换成Nan  
errrors='coerce' 遇到错误时报错  

In [50]:
#astype没有改变原始的数据框，而只是返回的一个拷贝
print(df.astype("float"))
df2=df.astype("str")
df3=df2.astype("float")

df2.apply(pd.to_numeric, errors='ignore')

    one   two  three  four
a   0.0   1.0    2.0   3.0
b   4.0   5.0    6.0   7.0
c   8.0   9.0   10.0  11.0
d  12.0  13.0   14.0  15.0


one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

# 生成pandas时间序列
| 别名    | Offset类型     | 描述                     |
| ------- | -------------- | ------------------------ |
| B       | BDay           | 工作日                   |
| C       | CDay           | 定制工作日               |
| D       | Day            | 日历日                   |
| W       | Week           | 每周                     |
| M       | MonthEnd       | 每月最后一个日历日       |
| SM      | SemiMonthEnd   | 每月15日和最后一个日历日 |
| BM      | BMonthEnd      | 每月15日和最后一个工作日 |
| CBM     | CBMonthEnd     | 定制每月最后一个日历日   |
| MSS     | MonthBegin     | 每月第一个日历日         |
| SMS     | SemiMonthBegin | 每月1日和15日            |
| BMS     | BMonthBegin    | 每月第一个工作日         |
| CBMS    | CBMonthBegin   | 定制每月第一个工作日     |
| Q       | QuarterEnd     | 每季度最后一个日历日     |
| BQ      | BQuarterEnd    | 每季度最后一个工作日     |
| QS      | QuarterBegin   | 每季度第一个日历日       |
| BQS     | BQuarterBegin  | 每季度第一个工作日       |
| A,Y     | YearEnd        | 每年最后一个日历日       |
| BA,BY   | BYearEnd       | 每年最后一个工作日       |
| AS,YS   | YearBegin      | 每年第一个日历日         |
| BAS,BYS | BYearBegin     | 每年第一个工作日         |
| H       | Hour           | 每小时                   |
| BH      | BusinessHour   | 每工作小时               |
| T,min   | Minute         | 每分钟                   |
| S       | Second         | 每秒                     |
| L,ms    | Milli          | 毫秒                     |
| U,us    | Micro          | 微秒                     |
| N       | Nano           | 纳秒                     |

In [105]:
import datetime
df=pd.date_range('2020-5-26',datetime.date.today(),freq='B')
print(df,"\n")

DatetimeIndex(['2020-05-26', '2020-05-27', '2020-05-28', '2020-05-29', '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04', '2020-06-05', '2020-06-08', '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12', '2020-06-15', '2020-06-16', '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25', '2020-06-26', '2020-06-29', '2020-06-30', '2020-07-01', '2020-07-02', '2020-07-03', '2020-07-06'], dtype='datetime64[ns]', freq='B') 



# 其它时间格式转换为pandas的时间格式

In [106]:
#时间戳转换
df=[1593344580.670537,1593344580.670537]
df=pd.to_datetime(df, unit='s')
print(df)

#时间戳转换
df=[1593344580670,1593344580670]
df=pd.to_datetime(df, unit='ms')
print(df)


#string转换
df=["2020-05-01","2020-05-02"]
df=pd.to_datetime(df,format="%Y-%m-%d")
print(df)

#string转换
df=["2020-05-01 20:00:00","2020-05-02 12:00:00"]
df=pd.to_datetime(df,format="%Y-%m-%d %H:%M:%S")
print(df)

DatetimeIndex(['2020-06-28 11:43:00.670536995', '2020-06-28 11:43:00.670536995'], dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2020-06-28 11:43:00.670000', '2020-06-28 11:43:00.670000'], dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2020-05-01', '2020-05-02'], dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2020-05-01 20:00:00', '2020-05-02 12:00:00'], dtype='datetime64[ns]', freq=None)


# pandas的时间格式转换为string

In [107]:
df2=df.strftime("%Y-%m-%d")
print(df2)

Index(['2020-05-01', '2020-05-02'], dtype='object')


# 将dataframe整体平移i个单元格创建一个新的dataframe
原dataframe自身不会产生变化，由此缺少的值用NaN填补

In [108]:
df=pd.DataFrame(np.arange(16).reshape((4,4)),index=['a','b','c','d'],columns=['one','two','three','four'])
#向下平移
df2=df.shift(1)
print(df2,"\n")

#向上平移
df2=df.shift(-1)
print(df2)

   one  two  three  four
a  NaN  NaN    NaN   NaN
b  0.0  1.0    2.0   3.0
c  4.0  5.0    6.0   7.0
d  8.0  9.0   10.0  11.0 

    one   two  three  four
a   4.0   5.0    6.0   7.0
b   8.0   9.0   10.0  11.0
c  12.0  13.0   14.0  15.0
d   NaN   NaN    NaN   NaN


# 移动5个值，进行求平均数（5日均线）

In [109]:
df=pd.DataFrame(np.arange(16),columns=['a'])
data=df
df["new"]=data.rolling(5).mean()
print(df)

     a   new
0    0   NaN
1    1   NaN
2    2   NaN
3    3   NaN
4    4   2.0
5    5   3.0
6    6   4.0
7    7   5.0
8    8   6.0
9    9   7.0
10  10   8.0
11  11   9.0
12  12  10.0
13  13  11.0
14  14  12.0
15  15  13.0


# 数据离散化

In [110]:
np.array([[1,2,3],[4,5,6]])
df=[20,22,25,27,21,23,37,31,61,45,41,32]
df=pd.DataFrame(np.arange(16).reshape((4,4)),index=['a','b','c','d'],columns=['one','two','three','four'])
bins = [0, 10, 20, 50,100]
p_counts = pd.cut(df, bins)
print(p_counts)
df.groupby(p_counts).count()

ValueError: Input array must be 1 dimensional