In [68]:
#!/usr/bin/python
# -*- coding: UTF-8 -*-
import numpy as np

# 矩阵形状

In [69]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

# 矩阵维度

In [70]:
a=np.array([[1,2,3],[4,5,6]])
a.ndim

2

# 矩阵元素个数

In [71]:
a=np.array([[1,2,3],[4,5,6]])
a.size

6

# 矩阵数据类型
uint8	无符号整数（0 to 255）  
int8	字节（-128 to 127）  
int16	整数（-32768 to 32767）  
int32	整数（-2147483648 to 2147483647）  
float16	半精度浮点数，包括：1 个符号位，5 个指数位，10 个尾数位  
float32	单精度浮点数，包括：1 个符号位，8 个指数位，23 个尾数位  

In [72]:
a=np.array([[1,2,3],[4,5,6]])
a.dtype

dtype('int32')

# 创建随机数构成的矩阵，元素是5个

In [73]:
print(np.random.rand(5))
print(np.random.rand(3,2))
#创建随机整数,low、high、size三个参数,省略low时默认low=0
np.random.randint(1,10,size=(3,3))

[0.43708397 0.59955795 0.697167   0.82377096 0.37199575]
[[0.74256218 0.84366405]
 [0.93950574 0.49056882]
 [0.45035748 0.88170975]]


array([[5, 9, 2],
       [4, 8, 6],
       [5, 5, 1]])

# 创建指定元素的矩阵

In [74]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

# 创建与范例一样shape的0矩阵

In [75]:
a=np.array([[1,2,3],[4,5,6]])
np.zeros_like(a, dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

# 创建5*2的矩阵，用0填充

In [76]:
np.zeros((5, 2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

# 创建5*2的矩阵，用1填充

In [77]:
np.ones((5, 2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# 创建5*2的空矩阵，仅仅分配矩阵所使用的内存，不对矩阵元素进行初始化操作，因此它的运行速度是最快的

In [78]:
np.empty((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# 按照步长创建矩阵，默认步长为1

In [79]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

# 指定步长为2的等差数列

In [80]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

# 指定元素个数为10个的等差数列

In [81]:
np.linspace(1,6,10)

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

# 对矩阵进行从小到大的排序

In [82]:
a=np.random.randint(10,size=(3,3))
print(a)
np.sort(a,axis=0)

[[9 9 2]
 [7 3 8]
 [2 4 6]]


array([[2, 3, 2],
       [7, 4, 6],
       [9, 9, 8]])

# 对矩阵进行从小到大的排序，返回对应的索引

In [83]:
a=np.random.randint(10,size=(3,3))
print(a)
np.argsort(a,axis=0)

[[5 8 3]
 [6 9 4]
 [6 0 5]]


array([[0, 2, 0],
       [1, 0, 1],
       [2, 1, 2]], dtype=int64)

# 返回矩阵最大值的索引

In [84]:
a=np.random.rand(3,3)
print(a)
np.argmax(a,axis=0)

[[0.51853738 0.5120777  0.80895996]
 [0.07660695 0.15318401 0.5903754 ]
 [0.02326655 0.57022913 0.25663538]]


array([0, 2, 0], dtype=int64)

# 使用切片方式获取的矩阵与原矩阵共享内存，修改一个另一个会同时变更

In [85]:
a=np.random.randint(10,size=(5,5,5))

print("[0,:,:]表示第一个3维数组，相当于正方体的第一个切面",a[0,:,:],'\n')
print("[1:3,:,:]表示第2个到第4个的3维数组",a[1:3,:,:],'\n')

[0,:,:]表示第一个3维数组，相当于正方体的第一个切面 [[2 3 9 1 2]
 [4 3 5 8 6]
 [7 0 4 2 0]
 [1 9 1 1 0]
 [4 8 0 8 8]] 

[1:3,:,:]表示第2个到第4个的3维数组 [[[8 8 4 3 6]
  [2 9 2 9 6]
  [2 5 6 9 5]
  [8 2 8 3 7]
  [9 6 7 0 9]]

 [[0 0 4 7 4]
  [2 8 8 5 1]
  [5 6 7 5 8]
  [9 9 0 4 6]
  [5 7 9 8 2]]] 



# 返回矩阵的一个复制,和原数组不共享内存

In [86]:
a=np.random.randint(10,size=(2,2))
a.copy()

array([[3, 2],
       [2, 6]])

# 转换数据类型

In [87]:
a=np.random.randint(10,size=(2,2))
print(a)
print(a.astype(np.float32))

[[4 5]
 [1 0]]
[[4. 5.]
 [1. 0.]]


# 浅层复制改变矩阵shape，(m,n,p) m*n*p等于原矩阵元素总个数
#reshape()为浅层复制，创建的数组和原数组不共享内存，改变一个数组，另一个不会同时改变  
参数-1表示该参数自动推算

In [88]:
a=np.random.randint(10,size=(2,3,15))
a.reshape(3,30)
a.reshape(-1,5)

array([[6, 9, 7, 5, 2],
       [9, 3, 8, 1, 6],
       [3, 0, 4, 4, 8],
       [3, 8, 1, 7, 5],
       [2, 9, 0, 2, 6],
       [3, 1, 3, 9, 8],
       [7, 5, 2, 0, 1],
       [8, 2, 2, 9, 1],
       [5, 1, 5, 2, 4],
       [1, 9, 4, 5, 1],
       [9, 2, 3, 2, 1],
       [3, 2, 4, 3, 5],
       [1, 6, 6, 1, 7],
       [4, 1, 9, 2, 3],
       [6, 9, 5, 1, 9],
       [9, 4, 6, 1, 2],
       [9, 5, 4, 3, 9],
       [1, 8, 9, 2, 6]])

# 深层复制改变矩阵shape，创建的矩阵和原矩阵共享内存，改变一个矩阵，另一个会同时改变

In [89]:
a=np.random.randint(10,size=(2,15))
a.resize(6,5)
print(a)

[[6 0 1 9 1]
 [7 2 3 1 9]
 [7 3 3 7 1]
 [4 2 2 0 3]
 [8 7 0 1 7]
 [1 4 5 9 3]]


# 将原矩阵横向、纵向地复制，tile 是瓷砖的意思

In [90]:
a=np.array([1,0,0])
np.tile(a,(4,1))

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

# 交换维度的顺序

In [91]:
a=np.random.randint(10,size=(2,3,4))
print(a.shape)
b=a.transpose(1,0,2)
print(b.shape)

(2, 3, 4)
(3, 2, 4)


# 元素顺序交换

In [92]:
rgb=np.ones((50,80,3),dtype=np.uint8)
bgr=rgb[:,:,[2,1,0]]

# 矩阵元素相加

In [93]:
a=np.random.randint(10,size=(2,2))
print(a)
a+a

[[8 8]
 [4 3]]


array([[16, 16],
       [ 8,  6]])

# 数组元素相乘

In [94]:
a=np.random.randint(10,size=(2,2))
print(a)
a*a

[[3 6]
 [3 6]]


array([[ 9, 36],
       [ 9, 36]])

# 数组元素相除，返回精确的商

In [95]:
a=np.random.randint(10,size=(2,2))
b=np.random.randint(1,10,size=(2,2))
a/b

array([[0.16666667, 1.        ],
       [0.4       , 1.25      ]])

# 数组元素相除，返回值取整

In [96]:
a=np.random.randint(10,size=(2,2))
b=np.random.randint(10,size=(2,2))
a//b

array([[0, 1],
       [0, 1]], dtype=int32)

# 矩阵元素进行逻辑运算生成布尔数组
可以使用的逻辑运算符号有<,<=,>,>=,==,!=

In [97]:
a=np.random.randint(10,size=(2,2))
print(a)
a>3

[[5 3]
 [0 8]]


array([[ True, False],
       [False,  True]])

# 矩阵转置

In [98]:
a=np.random.randint(10,size=(2,3))
print(a)
a.T

[[9 1 0]
 [1 5 2]]


array([[9, 1],
       [1, 5],
       [0, 2]])

# 矩阵连接

In [99]:
a=np.random.randint(10,size=(2,3))
print(a)
print("axis=0连接")
print(np.concatenate((a,a,a), axis=0))
print("axis=1连接")
print(np.concatenate((a,a,a), axis=1))

[[0 6 4]
 [7 7 6]]
axis=0连接
[[0 6 4]
 [7 7 6]
 [0 6 4]
 [7 7 6]
 [0 6 4]
 [7 7 6]]
axis=1连接
[[0 6 4 0 6 4 0 6 4]
 [7 7 6 7 7 6 7 7 6]]


# 获取矩阵元素1~5的坐标，根据查询结果，返回矩阵的shape是不定的

In [100]:
a=np.random.randint(10,size=(2,3))
print(a)
np.where((a<=5)&(a>=1))

[[6 9 7]
 [5 4 6]]


(array([1, 1], dtype=int64), array([0, 1], dtype=int64))

# 获取x<=5的数据

In [101]:
a=np.random.randint(10,size=(2,3))
print(a)
a[np.where(a<=5)]

[[7 8 0]
 [9 5 2]]


array([0, 5, 2])

# 将小于5的元素赋值1，将其它元素赋值255

In [102]:
a=np.random.randint(10,size=(2,3))
print(a)
b=np.where(a < 5,1,255)
print(b)
#将小于5的元素赋值1，将其它元素不变
np.where(a < 5,1,a)

[[2 8 5]
 [9 9 9]]
[[  1 255 255]
 [255 255 255]]


array([[1, 8, 5],
       [9, 9, 9]])

# 数据离散化
#bin是区间数据，必须为递增数列或递减数列。
#data为要判别的数据
#np.disitize返回值为数据在第几个区间

In [104]:
data=np.array([0.2,6.4,3.0,1.6])
bins=np.array([0,1,2.5,4,10])
cats=np.digitize(data,bins)
print(cats,'\n')

返回数据在第几个区间
[1 4 3 2] 

