In [2]:
#!/usr/bin/python
# -*- coding: UTF-8 -*-
import numpy as np

# 矩阵形状

In [179]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

# 矩阵维度

In [180]:
a=np.array([[1,2,3],[4,5,6]])
a.ndim

2

# 矩阵元素个数

In [181]:
a=np.array([[1,2,3],[4,5,6]])
a.size

6

# 矩阵数据类型
uint8	无符号整数（0 to 255）  
int8	字节（-128 to 127）  
int16	整数（-32768 to 32767）  
int32	整数（-2147483648 to 2147483647）  
float16	半精度浮点数，包括：1 个符号位，5 个指数位，10 个尾数位  
float32	单精度浮点数，包括：1 个符号位，8 个指数位，23 个尾数位  

In [182]:
a=np.array([[1,2,3],[4,5,6]])
a.dtype

dtype('int32')

# 创建随机数构成的矩阵，元素是5个

In [216]:
print(np.random.rand(5))
print(np.random.rand(3,2))
#创建随机整数,low、high、size三个参数,省略low时默认low=0
np.random.randint(1,10,size=(3,3))

[0.62508035 0.43409203 0.11675395 0.08994752 0.50503045]
[[0.83630708 0.56552849]
 [0.89533337 0.60330445]
 [0.70921178 0.57154934]]


array([[4, 1, 3],
       [3, 4, 8],
       [2, 7, 8]])

# 创建指定元素的矩阵

In [184]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

# 创建与范例一样shape的0矩阵

In [185]:
a=np.array([[1,2,3],[4,5,6]])
np.zeros_like(a, dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

# 创建5*2的矩阵，用0填充

In [186]:
np.zeros((5, 2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

# 创建5*2的矩阵，用1填充

In [187]:
np.ones((5, 2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# 创建5*2的空矩阵，仅仅分配矩阵所使用的内存，不对矩阵元素进行初始化操作，因此它的运行速度是最快的

In [188]:
np.empty((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# 按照步长创建矩阵，默认步长为1

In [189]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

# 指定步长为2的等差数列

In [190]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

# 指定元素个数为10个的等差数列

In [191]:
np.linspace(1,6,10)

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

# 对矩阵进行从小到大的排序

In [192]:
a=np.random.randint(10,size=(3,3))
print(a)
np.sort(a,axis=0)

[[1 3 3]
 [4 7 7]
 [5 4 8]]


array([[1, 3, 3],
       [4, 4, 7],
       [5, 7, 8]])

# 对矩阵进行从小到大的排序，返回对应的索引

In [193]:
a=np.random.randint(10,size=(3,3))
print(a)
np.argsort(a,axis=0)

[[7 8 2]
 [9 0 3]
 [7 6 2]]


array([[0, 1, 0],
       [2, 2, 2],
       [1, 0, 1]], dtype=int64)

# 返回矩阵最大值的索引

In [23]:
a=np.random.rand(3,3)
print(a)
np.argmax(a,axis=0)

[[0.48450119 0.9978226  0.59960105]
 [0.31642767 0.78604546 0.45185827]
 [0.26132824 0.88702066 0.64023671]]


array([0, 0, 2], dtype=int64)

# 使用切片方式获取的矩阵与原矩阵共享内存，修改一个另一个会同时变更

In [194]:
a=np.random.randint(10,size=(5,5,5))

print("[0,:,:]表示第一个3维数组，相当于正方体的第一个切面",a[0,:,:],'\n')
print("[1:3,:,:]表示第2个到第4个的3维数组",a[1:3,:,:],'\n')

[0,:,:]表示第一个3维数组，相当于正方体的第一个切面 [[7 1 9 9 6]
 [8 7 1 9 8]
 [8 6 6 8 0]
 [0 3 5 0 6]
 [0 9 6 4 7]] 

[1:3,:,:]表示第2个到第4个的3维数组 [[[2 6 2 7 7]
  [1 7 1 1 5]
  [6 1 6 9 8]
  [3 2 9 7 0]
  [9 2 3 2 5]]

 [[5 5 7 9 5]
  [4 8 8 7 4]
  [5 7 4 6 0]
  [1 1 3 3 7]
  [6 0 5 8 0]]] 



# 返回矩阵的一个复制,和原数组不共享内存

In [195]:
a=np.random.randint(10,size=(2,2))
a.copy()

array([[5, 2],
       [1, 5]])

# 转换数据类型

In [196]:
a=np.random.randint(10,size=(2,2))
print(a)
print(a.astype(np.float32))

[[9 0]
 [8 5]]
[[9. 0.]
 [8. 5.]]


# 浅层复制改变矩阵shape，(m,n,p) m*n*p等于原矩阵元素总个数
#reshape()为浅层复制，创建的数组和原数组不共享内存，改变一个数组，另一个不会同时改变

In [197]:
a=np.random.randint(10,size=(2,15))
a.reshape(6,5)

array([[3, 9, 7, 0, 0],
       [5, 8, 0, 4, 6],
       [3, 6, 6, 8, 3],
       [5, 7, 8, 7, 0],
       [2, 6, 9, 2, 8],
       [0, 0, 5, 0, 0]])

# 深层复制改变矩阵shape，创建的矩阵和原矩阵共享内存，改变一个矩阵，另一个会同时改变

In [198]:
a=np.random.randint(10,size=(2,15))
a.resize(6,5)
print(a)

[[9 8 6 7 7]
 [1 1 4 0 3]
 [6 3 8 2 2]
 [2 7 0 7 5]
 [3 7 9 8 0]
 [4 4 9 3 1]]


# 交换维度的顺序

In [199]:
a=np.random.randint(10,size=(2,3,4))
print(a.shape)
b=a.transpose(1,0,2)
print(b.shape)

(2, 3, 4)
(3, 2, 4)


# 元素顺序交换

In [200]:
rgb=np.ones((50,80,3),dtype=np.uint8)
bgr=rgb[:,:,[2,1,0]]

# 矩阵元素相加

In [201]:
a=np.random.randint(10,size=(2,2))
print(a)
a+a

[[1 3]
 [2 5]]


array([[ 2,  6],
       [ 4, 10]])

# 数组元素相乘

In [202]:
a=np.random.randint(10,size=(2,2))
print(a)
a*a

[[1 8]
 [4 6]]


array([[ 1, 64],
       [16, 36]])

# 数组元素相除，返回精确的商

In [217]:
a=np.random.randint(10,size=(2,2))
b=np.random.randint(1,10,size=(2,2))
a/b

array([[0.33333333, 1.14285714],
       [0.875     , 4.        ]])

# 数组元素相除，返回值取整

In [204]:
a=np.random.randint(10,size=(2,2))
b=np.random.randint(10,size=(2,2))
a//b

array([[1, 0],
       [0, 3]], dtype=int32)

# 矩阵元素进行逻辑运算生成布尔数组
可以使用的逻辑运算符号有<,<=,>,>=,==,!=

In [205]:
a=np.random.randint(10,size=(2,2))
print(a)
a>3

[[1 9]
 [8 6]]


array([[False,  True],
       [ True,  True]])

# 矩阵转置

In [206]:
a=np.random.randint(10,size=(2,3))
print(a)
a.T

[[9 9 6]
 [4 1 2]]


array([[9, 4],
       [9, 1],
       [6, 2]])

# 矩阵连接

In [207]:
a=np.random.randint(10,size=(2,3))
print(a)
print("axis=0连接")
print(np.concatenate((a,a,a), axis=0))
print("axis=1连接")
print(np.concatenate((a,a,a), axis=1))

[[7 0 8]
 [3 8 8]]
axis=0连接
[[7 0 8]
 [3 8 8]
 [7 0 8]
 [3 8 8]
 [7 0 8]
 [3 8 8]]
axis=1连接
[[7 0 8 7 0 8 7 0 8]
 [3 8 8 3 8 8 3 8 8]]


# 获取矩阵元素1~5的坐标，根据查询结果，返回矩阵的shape是不定的

In [208]:
a=np.random.randint(10,size=(2,3))
print(a)
np.where((a<=5)&(a>=1))

[[9 6 0]
 [3 5 3]]


(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))

# 获取x<=5的数据

In [209]:
a=np.random.randint(10,size=(2,3))
print(a)
a[np.where(a<=5)]

[[6 2 8]
 [6 1 7]]


array([2, 1])

# 将小于5的元素赋值1，将其它元素赋值255

In [210]:
a=np.random.randint(10,size=(2,3))
print(a)
np.where(a < 5,1,255)

[[3 4 3]
 [4 4 7]]


array([[  1,   1,   1],
       [  1,   1, 255]])