In [2]:
#!/usr/bin/python
# -*- coding: UTF-8 -*-
from keras import backend as K
import numpy as np
import tensorflow as tf

Using TensorFlow backend.


# 张量与矩阵的相互转换

In [43]:
a=np.array([[1,2,3],[4,5,6]])
#将矩阵转换为张量
var1=K.variable(value=a,dtype="float32")
print(var1.shape)
K.eval(var1)

(2, 3)


array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

# 在下标为dim的轴上增加一维

In [9]:
print(var1.shape)
var2=K.expand_dims(var1,axis = 0)
print(var2.shape)

(2, 3)
(1, 2, 3)


## 创建一个用[9,1,1]平铺的var2张量

In [13]:
print(var2)
var4=K.tile(var2,[9,1,1])
print(var4)

#快速复制张量
var6=K.tile(K.expand_dims(var1,axis = 0),[9,1,1])
print(var6)

Tensor("ExpandDims:0", shape=(1, 2, 3), dtype=float32)
Tensor("Tile_5:0", shape=(9, 2, 3), dtype=float32)
Tensor("Tile_6:0", shape=(9, 2, 3), dtype=float32)


# 在下标为dim的轴上增加一维

In [11]:
print(var1.shape)
var3=K.expand_dims(var1,axis = 1)
print(var3.shape)

(2, 3)
(2, 1, 3)
Tensor("Tile_2:0", shape=(2, 2, 3), dtype=float32)


## 创建一个用[1,9,1]平铺的var3张量

In [14]:
print(var3)
var5=K.tile(var3,[1,9,1])
print(var5)


#快速复制张量
var6=K.tile(K.expand_dims(var1,axis = 1),[1,9,1])
print(var6)

Tensor("ExpandDims_2:0", shape=(2, 1, 3), dtype=float32)
Tensor("Tile_7:0", shape=(2, 9, 3), dtype=float32)
Tensor("Tile_8:0", shape=(2, 9, 3), dtype=float32)


# 对各个元素进行底数为e的指数运算

In [42]:
print(K.eval(var1))
K.eval(K.exp(var1))

[[1. 2. 3.]
 [4. 5. 6.]]


array([[  2.7182817,   7.389056 ,  20.085537 ],
       [ 54.59815  , 148.41316  , 403.4288   ]], dtype=float32)

# 求张量的最大值

In [41]:
print(K.eval(var1))
K.eval(K.max(var1))

[[1. 2. 3.]
 [4. 5. 6.]]


6.0

# 逐个元素对比两个张量，取较大值。如果是常量，则与与该常量逐个对比取较大值

In [40]:
print(K.eval(K.exp(var1)))
K.eval(K.exp(K.maximum(var1,4)))

[[  2.7182817   7.389056   20.085537 ]
 [ 54.59815   148.41316   403.4288   ]]


array([[ 54.59815,  54.59815,  54.59815],
       [ 54.59815, 148.41316, 403.4288 ]], dtype=float32)

# K.cast(x, dtype)转换张量的数据类型

In [91]:
var=K.variable(value=np.array([False,True]),dtype="bool")
print(K.eval(var))
var=K.cast(var, dtype="int32")
K.eval(var)

[False  True]


array([0, 1])

# K.sum求张量内所有元素的和
axis = -2 对应 axis = 0,效果一致；  
axis = -1 对应 axis = 1,效果一致；

In [47]:
var=np.random.randint(10,size=(2,2))
var=K.variable(value=var,dtype="uint8")
print(K.eval(var))
#所有元素求和
print(K.eval(K.sum(var)))
#按axis求和
print(K.eval(K.sum(var,axis=0, keepdims=True)))
print(K.eval(K.sum(var,axis=1, keepdims=True)))
print(K.eval(K.sum(var,axis=-1, keepdims=True)))

[[9 6]
 [1 6]]
22
[[10 12]]
[[15]
 [ 7]]
[[15]
 [ 7]]


# 生成服从正态分布的随机张量,mean为均值，std为标准差

In [88]:
var=K.random_normal(shape=(2,2),mean=0.,stddev=1.0)
print(K.eval(var))
#注意每次print时均会重新取值
print(K.eval(var))

[[ 0.31489232 -0.20817436]
 [ 0.00971632  0.9129183 ]]
[[-1.081441   -0.9185018 ]
 [ 0.87874234 -1.2285942 ]]


# 生成均匀分布的张量,minval为最小值，maxval为最大值

In [90]:
var=K.random_uniform(shape=(2,2),minval=0.,maxval=1.0)
print(K.eval(var))
#注意每次print时均会重新取值
print(K.eval(var))

[[0.32498205 0.8851963 ]
 [0.5817976  0.37890995]]
[[0.7202232  0.3799771 ]
 [0.81245685 0.02957261]]


# ones_like生成与目标shape一致的全1张量

In [50]:
kvar=K.random_uniform(shape=(2,2),minval=0.,maxval=1.0)
kvar=K.ones_like(kvar)
print(K.eval(kvar))

[[1. 1.]
 [1. 1.]]


# K.greater 比较张量的大小生成bool值的张量

In [85]:
var1=K.random_uniform(shape=(1,5),minval=0.,maxval=10.)
print(K.eval(K.greater(var1,3.0)))

[[ True  True  True  True False]]


# 返回一个大于0的极小浮点数，防止除0错误

In [ ]:
K.epsilon()

# 欧式距离$d_{12}=\sqrt{\sum_{k=1}^{n}\left(x_{1 k}-x_{2 k}\right)^{2}}$

In [49]:
var1=np.asarray([6.5,4.2,7.4,3.5],np.float32)
var2=np.array([1,3,2,5],np.float32)
kvar1=K.variable(value=var1,dtype="float32")
kvar2=K.variable(value=var2,dtype="float32")

#使用公式求解
L=K.sqrt(K.sum(K.square(kvar1-kvar2)))
print("欧式距离 ：",K.eval(L))

欧式距离 ： 7.9435506


# 计算张量的softmax值(每行转换为总和为1的概率分布）
$
假设我们有一个数组，V，Vi表示V中的第i个元素，那么这个元素的Softmax值就是  S_{i}=\frac{e^{V_{i}}}{\sum_{j} e^{V_{j}}}
$

In [11]:
var=K.random_uniform(shape=(2,2),minval=5,maxval=10)
print(K.eval(var))
var=K.softmax(var)
print(K.eval(var))

[[9.701295  5.4655223]
 [7.227085  6.6768413]]
[[0.34215495 0.657845  ]
 [0.97683674 0.02316327]]
[0.47536692 0.17487772 0.17487772 0.17487772]


# MSE(均方差)   
$M S E=S S E / n=\frac{1}{n} \sum_{i=1}^{n} w_{i}\left(y_{i}-\hat{y}_{i}\right)^{2}$

In [54]:
var1=np.asarray([6.5,4.2,7.4,3.5],np.float32)
var2=np.array([1,0,0,0],np.float32)
kvar1=K.variable(value=var1,dtype="float32")
kvar2=K.variable(value=var2,dtype="float32")

#使用keras预置的损失函数
from keras import losses
loss=K.eval(losses.mean_squared_error(kvar2,kvar1))
print("loss:",loss)

loss: 28.725


# MSLE（均方对数损失）
msle相比与mse的改进:如果想要预测的值范围很大,mse会受到一些大的值的引导,即使小的值预测准也不行

In [70]:
var1=np.asarray([6.5,4.2,7.4,3.5],np.float32)
var2=np.array([1,0,0,0],np.float32)
kvar1=K.variable(value=var1,dtype="float32")
kvar2=K.variable(value=var2,dtype="float32")

#使用keras预置的损失函数
from keras import losses
loss=K.eval(losses.mean_squared_logarithmic_error(kvar2,kvar1))
print("loss:",loss)

loss: 2.8141832


# RMSE(均方根)
$R M S E=\sqrt{M S E}=\sqrt{S S E / n}=\sqrt{\frac{1}{n} \sum_{i=1}^{n} w_{i}\left(y_{i}-\hat{y}_{i}\right)^{2}}$

In [67]:
var1=np.asarray([6.5,4.2,7.4,3.5],np.float32)
var2=np.array([1,0,0,0],np.float32)
kvar1=K.variable(value=var1,dtype="float32")
kvar2=K.variable(value=var2,dtype="float32")

#使用keras预置的损失函数
from keras import losses
loss=K.sqrt(losses.mean_squared_error(kvar2,kvar1))
print("loss:",K.eval(loss))

loss: 5.359571


# MAE(平均绝对误差)
$\mathrm{MAE}=\frac{\sum_{i=1}^{n}\left|y_{i}-x_{i}\right|}{n}$

In [68]:
var1=np.asarray([6.5,4.2,7.4,3.5],np.float32)
var2=np.array([1,0,0,0],np.float32)
kvar1=K.variable(value=var1,dtype="float32")
kvar2=K.variable(value=var2,dtype="float32")

#使用keras预置的损失函数
from keras import losses
loss=K.eval(losses.mean_absolute_error(kvar2,kvar1))
print("loss:",loss)

loss: 5.15


# binary_crossentropy计算两个张量的二分类交叉熵,默认输入的张量应该是进行了概率编码的张量（总和为1）

In [52]:
var1=np.asarray([6.5,4.2,7.4,3.5],np.float32)
var2=np.array([1,0,0,0],np.float32)
kvar1=K.variable(value=var1,dtype="float32")
kvar2=K.variable(value=var2,dtype="float32")

#使用keras预置的损失函数
from keras import losses
#参数1为真实分布（需要进行独热编码）
#参数2为预测值（需要进行softmax编码）
loss=K.eval(losses.binary_crossentropy(kvar2,K.softmax(kvar1)))
print("二分类交叉熵:",loss)

二分类交叉熵: 0.6173691


# categorical_crossentropy计算两个张量的多分类交叉熵，需要注意p，q的顺序，交换顺序会导致结果变化
$
H(p, q)=-\sum_{x} p(x) \log q(x)
$  
p为真实分布，q为非真实分布(预测值)

In [12]:
var1=np.asarray([6.5,4.2,7.4,3.5],np.float32)
var2=np.array([1,0,0,0],np.float32)

#方法一：使用numpy求解
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=0)
loss1=-np.sum(var2*np.log(softmax(var1)))
print("loss1:",loss1)



kvar1=K.variable(value=var1,dtype="float32")
kvar2=K.variable(value=var2,dtype="float32")
print("kvar1\n",K.eval(kvar1))
print("kvar2\n",K.eval(kvar2))

#方法二：使用tensorflow求解
sess=tf.Session()
sess.run(tf.global_variables_initializer())
#参数1为真实分布（需要进行独热编码）
#参数2为预测值（不需要进行softmax编码）
loss2=sess.run(tf.losses.softmax_cross_entropy(kvar2,kvar1))
sess.close()
print("loss2:",loss2)

#另一种方法
sess=tf.Session()
sess.run(tf.global_variables_initializer())
#参数1为真实分布（需要进行独热编码）
#参数2为预测值（不需要进行softmax编码）
loss2_2=sess.run(tf.nn.softmax_cross_entropy_with_logits(labels=kvar2, logits=kvar1))
sess.close()
print("loss2_2:",loss2_2)

#方法三：使用keras预置的损失函数
from keras import losses
#参数1为真实分布（需要进行独热编码）
#参数2为预测值（需要进行softmax编码）
loss3=K.eval(losses.categorical_crossentropy(kvar2,K.softmax(kvar1)))
print("loss3:",loss3)

loss1: 1.2836106
kvar1
 [6.5 4.2 7.4 3.5]
kvar2
 [1. 0. 0. 0.]
loss2: 1.2836106
loss2_2: 1.2836106
loss3: 1.2836106


# KL散度又称为相对熵，是交叉熵与信息熵的差值，相对熵=交叉熵-信息熵
$
D(p \| q)=\sum_{i=1}^{n} p(x) \log \frac{p(x)}{q(x)}
$   
p为真实分布，q为非真实分布(预测值)，KL散度是不对称的，交换p、q值会变化

In [31]:
var1=np.asarray([6.5,4.2,7.4,3.5],np.float32)
var2=np.array([1,3,2,5],np.float32)

#方法一：使用numpy求解
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=0)
loss1=np.sum(softmax(var2)*np.log(softmax(var2)/softmax(var1)))
print("loss1：",loss1)

kvar1=K.variable(value=var1,dtype="float32")
kvar2=K.variable(value=var2,dtype="float32")
kvar1=K.softmax(kvar1)
kvar2=K.softmax(kvar2)
print("kvar1\n",K.eval(kvar1))
print("kvar2\n",K.eval(kvar2))

#方法二：使用keras手工计算，kullback_leibler_divergence
loss2=K.sum(kvar2*K.log(kvar2/kvar1))
print("loss2:",K.eval( loss2))


#方法三：使用keras预置的损失函数
from keras import losses
#参数1为真实分布（需要进行softmax编码）
#参数2为预测值（需要进行softmax编码）
loss3=losses.kullback_leibler_divergence(kvar2,kvar1)
print("loss3:",K.eval( loss3))

loss1： 3.4028
kvar1
 [0.27703524 0.02777523 0.6813968  0.01379277]
kvar2
 [0.01521943 0.11245721 0.04137069 0.83095264]
loss2: 3.4027998
loss3: 3.4027998


# JS散度在KL散度的基础上进行了改进，具有对称性
$J S\left(P_{1} \| P_{2}\right)=\frac{1}{2} K L\left(P_{1} \| \frac{P_{1}+P_{2}}{2}\right)+\frac{1}{2} K L\left(P_{2} \| \frac{P_{1}+P_{2}}{2}\right)$  
p为真实分布，q为非真实分布(预测值)

In [36]:
var1=np.asarray([6.5,4.2,7.4,3.5],np.float32)
var2=np.array([1,3,2,5],np.float32)

#方法一：使用numpy求解
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=0)
loss1=0.5*np.sum(softmax(var2)*np.log(softmax(var2)/softmax(var1)))+0.5*np.sum(softmax(var1)*np.log(softmax(var1)/softmax(var2)))
print("loss1：",loss1)

kvar1=K.variable(value=var1,dtype="float32")
kvar2=K.variable(value=var2,dtype="float32")
kvar1=K.softmax(kvar1)
kvar2=K.softmax(kvar2)
print("kvar1\n",K.eval(kvar1))
print("kvar2\n",K.eval(kvar2))

#方法二：使用keras手工计算，kullback_leibler_divergence
loss2=0.5*K.sum(kvar2*K.log(kvar2/kvar1))+0.5*K.sum(kvar1*K.log(kvar1/kvar2))
print("loss2:",K.eval( loss2))

#方法三：使用keras预置的损失函数
from keras import losses
loss3=0.5*losses.kullback_leibler_divergence(kvar2,kvar1)+0.5*losses.kullback_leibler_divergence(kvar1,kvar2)
print("loss3:",K.eval( loss3))

loss1： 3.010124683380127
kvar1
 [0.27703524 0.02777523 0.6813968  0.01379277]
kvar2
 [0.01521943 0.11245721 0.04137069 0.83095264]
loss2: 3.0101247
loss3: 3.0101247


## Wasserstein 距离简称EMD，用来表示两个分布的相似程度。衡量了把数据从分布“移动成”分布时所需要移动的平均距离的最小值（类似于把一堆土从一个形状移动到另一个形状所需要做的功的最小值），Wasserstein 距离相比js散度的优点在于即使两个分布没有重叠，或重叠的部分很小，仍能反映两个分布的远近
我们可以构造一个含参数w、最后一层不是非线性激活层的判别器网络f_w，在限制w不超过某个范围的条件下，使得

$L = \mathbb{E}_{x \sim P_r} [f_w(x)] - \mathbb{E}_{x \sim P_g} [f_w(x)]$尽可能取到最大，此时L就会近似真实分布与生成分布之间的Wasserstein距离